# -*- coding: utf-8 -*-
"""Ejercicios Humai Python Tipos de datos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jyjK6cxFSy4AiACP9BMT-G_aGQrw9Bn8

<a href="https://colab.research.google.com/github/institutohumai/cursos-python/blob/master/Introduccion/1_TiposDatos/ejercicio/ejercicios.ipynb"> <img src='https://colab.research.google.com/assets/colab-badge.svg' /> </a>
<div align="center"> Recordá abrir en una nueva pestaña </div>

### 1. Definí $a = 5$, $b = 7$ y $c = 8$. Comprobá mediante operaciones booleanas si la suma de los dos primeros es mayor al tercero y, simultáneamente, si esa suma es un número par.
"""

a=5
b=7
c=8

(a+b) > c
(a+b) % 2 == 0

"""###2. Dado el string `sensor_data = "TEMP:22.5C|PRES:1013hPa"`, extraé únicamente el valor numérico de la temperatura utilizando slicing y convertilo a tipo `float`."""

sensor_data = "TEMP:22.5C|PRES:1013hPa"
temp = float (sensor_data [5:9])
print (temp)
print (type(temp))

"""###3.Tomá el string de la sinopsis (separado por pipes `|`) y reemplazá todos los pipes por saltos de línea (`\n`) para que el texto sea legible al mostrarlo."""

string = 'Sinopsis | Marty McFly, un típico adolescente americano de los años ochenta, '\
'es accidentalmente enviado de vuelta a 1955 en una "máquina del tiempo" realizada con'\
'un DeLorean inventada por un científico un poco loco. | En este viaje, Marty debe '\
'asegurarse de que sus padres se encuentren y se enamoren, para que pueda volver a su tiempo. '

string_limpia = string.replace("|", "\n")

print(string_limpia)

"""###4. Dada la lista de edades `[30, 40, 38, 30, 37]`, calculá el promedio de edad utilizando las funciones `sum()` y `len()`.

"""

edades = [30, 40, 38, 30, 37]
sum (edades)
len (edades)

prom_edades = (sum(edades)) / len (edades)
print (prom_edades)

"""###5. Creá un diccionario con tres constantes físicas ($g = 9.8$, $c = 299792458$, $G = 6.674e-11$). Pedí al usuario el nombre de una constante y devolvé su valor numérico."""

const_fisicas = {"g":9.8, "c":299792458, "G":6.67411}
busqueda = input ("Inserte el nombre de una constante (g, c o G):: ")

if busqueda in const_fisicas:
    print (f"El número de {busqueda} es {const_fisicas[busqueda]}")
else :
  print ("el valor no pertenece a una constante física")

"""###6. Escribí un código que tome una lista de nombres y devuelva una nueva lista donde cada nombre esté escrito al revés (ej: "Python" -> "nohtyP")."""

lista_nombres = ["Python", "Modelo", "Humai", "Artificial"]

lista_nombres_invertidos = [nombre[::-1] for nombre in lista_nombres]
print(lista_nombres_invertidos)


lista_invertidos = [palabra[::-1] for palabra in lista_nombres]
print (lista_invertidos)

"""### 7. Crear un acrónimo (una palabra compuesta por la primera letra de cada palabra) de cada título. Recordar que es necesario que transformemos los títulos a "title case" porque no todos van a llegar prolijos. Entonces, el acrónimo de "Volver al futuro" debería ser "VAF".

### Devolver una lista con todos los acronimos, ordenados alfabeticamente

"""

peliculas = [
    "Volver al futuro",
    "El señor de los anillos",
    "La guerra de las galaxias",
    "El juego de la imitacion",
    "Una mente brillante",
    "El club de la pelea",
    "Buscando a Nemo",
    "El viaje de Chihiro"
]

titulo = "volver al futuro"

titulo_prolijo = titulo.title()
print (titulo_prolijo)
palabras = titulo_prolijo.split()
print (palabras)
letras_iniciales = [palabra[0] for palabra in palabras]
print (letras_iniciales)
acronimo = "".join (letras_iniciales)
print (acronimo)

lista_acronimos=[]
for titulo in peliculas:
    palabras=titulo.title().split()
    iniciales = [palabra[0] for palabra in palabras]
    acronimo = "".join(iniciales)
    lista_acronimos.append(acronimo)
    acronimos_ordenados = sorted(lista_acronimos)
print (acronimos_ordenados)

"""###8. Creá un diccionario donde las llaves sean nombres de usuario y los valores sean contraseñas. Escribí un programa que verifique si un usuario ingresado existe y si su contraseña es correcta.

### Si el usuario no existe, agregalo al diccionario
"""

personas = {"pepito": "pepi123", "carola": "manzana" , "Gabi1994" : "caro123" }

usuario_ingresa = input ("ingrese su nombre de usuario:")

if usuario_ingresa in personas:

    contraseña_ingresa = input ("Ingrese su contraseña:")
    if contraseña_ingresa == personas [usuario_ingresa]:
     print (f"Bienvenido {usuario_ingresa}")
    else:
       print ("Su contraseña es incorrecta")

else:
   print ("su usuario no pertenece a la base de datos")

